### ISSUE TITLE
Error during Installation with Helm Chart

### ISSUE THREAD

**Issue by mschoeppe** [djkormo/adcs-issuer#35]
Using the 2.0.5 Helm Chart for installation, I'm getting this error

> ts=2023-11-29T08:42:03.489508343Z level=info logger=setup msg="Starting ADCS Issuer" version=adcs-operator-by-djkormo buildtime=2022-12-18:11:00
> ts=2023-11-29T08:42:03.489879343Z level=error logger=controller-runtime.client.config msg="unable to get kubeconfig" error="invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable" errorCauses="[\"error=\\\"no configuration has been provided, try setting KUBERNETES_MASTER environment variable\\\"\"]" stacktrace="sigs.k8s.io/controller-runtime/pkg/client/config.GetConfigOrDie\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/client/config/config.go:153\nmain.main\n\t/workspace/main.go:112\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255"

As far as I can tell, the missing "KUBERNETES_MASTER" variable is never set during installation.

Current Environment:
-Kubernetes v1.24.10 RKE2 Cluster 
-Rancher 2.7.0
-Certmanager 1.12.0

**Comment by helletheone** [comment]
i have the same issue!

**Comment by djkormo** [comment]
Ok, I'll try to recreate

**Comment by djkormo** [comment]
Try to use helm chart version 2.0.7 with values.yaml
```yaml
crd:
  install: true

controllerManager:
  manager:
    image:
      repository: djkormo/adcs-issuer
      tag: 2.0.5
    resources:
      limits:
        cpu: 100m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 100Mi

  rbac:
    enabled: true
    serviceAccountName: adcs-issuer


  replicas: 1

  environment:
    KUBERNETES_CLUSTER_DOMAIN: cluster.local
    ENABLE_WEBHOOKS: "false"
    ENABLE_DEBUG: "false"
  arguments:
    - --enable-leader-election=true
    - --cluster-resource-namespace=cert-manager
    - --zap-log-level=5
    - --disable-approved-check=false

  securityContext:
    runAsUser: 1000

  enabledWebHooks: false
  enabledCaCerts: false
  caCertsSecretName: ca-certificates
metricsService:
  enabled: true
  ports:
  - name: https
    port: 8443
    targetPort: https
  type: ClusterIP
webhookService:
  ports:
  - port: 443
    targetPort: 9443
  type: ClusterIP
```
