### ISSUE TITLE
Incorrect example for Ingress: AdcsClusterIssuer->ClusterAdcsIssuer

### ISSUE THREAD

**Issue by aryndin9999** [djkormo/adcs-issuer#67]
There is an example on https://github.com/djkormo/adcs-issuer

metadata:
  name: test-ingress
    annotations:
        cert-manager.io/issuer: "adcs-issuer" #use specific name of issuer
        cert-manager.io/issuer-kind: "AdcsIssuer" #or AdcsClusterIssuer
        cert-manager.io/issuer-group: "adcs.certmanager.csf.nokia.com"

Need to correct 

metadata:
  name: test-ingress
    annotations:
        cert-manager.io/issuer: "adcs-issuer" #use specific name of issuer
        cert-manager.io/issuer-kind: "AdcsIssuer" #or **ClusterAdcsIssuer**
        cert-manager.io/issuer-group: "adcs.certmanager.csf.nokia.com"

**Comment by djkormo** [comment]
Could you paste correct manifest as yaml code block ?
```yaml
metadata:
  name: name: test-ingress
  # .... #
```

**Comment by jamallorock** [comment]
@aryndin9999  Is this issue still valid?

**Comment by aryndin9999** [comment]
> Could you paste correct manifest as yaml code block ?
> 
> ```yaml
> metadata:
>   name: name: test-ingress
>   # .... #
> ```

Correct manifest 

```yaml
metadata:
  name: test-ingress
    annotations:
        cert-manager.io/issuer: "adcs-issuer" #use specific name of issuer
        cert-manager.io/issuer-kind: "AdcsIssuer" #or AdcsClusterIssuer
        cert-manager.io/issuer-group: "adcs.certmanager.csf.nokia.com"
```
